---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: provider
  labels:
    app.kubernetes.io/part-of: provider
    apps.tanzu.vmware.com/workload-type: web
spec:
  build:
    env:
      - name: BP_DOTNET_PROJECT_PATH
        value: "./Provider.Api"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/min-scale: "1"
  source:
    git:
      url: https://github.com/th3n3rd/tap-recipe-dotnet-ext-config.git
      ref:
        branch: main
    subPath: Provider
